float32_matmul_precision: highest
fp16: true
backbone:
  backbone: dinov2
  patch_size: 14
  embed_dim: 1024
  depth: 24
  num_heads: 16
  mlp_ratio: 4.0
  drop_path_rate: 0.1
  output_layers: [4, 11, 17, 23]
  include_cls_token: false
  include_task_token: false
  backbone_pretrained_path: /home/carmelo/RICERCA/INSAIT/ConvAtt_repo/weights/dinov2_vitl14_pretrain.pth
  pretrained_img_size: 518
  learnable_pos_embed: false
  num_register_tokens: 0

convatt:
  enabled: true

  conv_style: depthwise # full, depthwise
  conv_granularity: scattered # blockwise, scattered
  head_ensembling: false # true, false
  conv_selection: manual # manual, dsp

  heads:   {0: [15, 11, 12, 5, 10, 3], 1: [14, 15, 6, 13, 8, 7, 12, 5, 0, 2, 9, 4, 10], 4: [4, 2, 3, 10, 11, 8, 9, 0, 12, 15, 6, 7, 13, 1, 14], 9: [13, 12, 15, 10, 5, 14, 9, 6, 11, 1, 4, 0, 7], 6: [12, 8, 0, 11, 1, 4, 7, 6, 9, 10, 3, 2, 13, 5, 14], 8: [9, 0, 7, 10, 12, 14, 1, 8, 13, 6, 11, 3, 2, 5], 7: [10, 13, 2, 7, 6, 11, 5, 15, 14, 8, 4, 3, 0, 9, 1, 12], 2: [12, 8, 0, 2, 3, 7, 6, 9], 10: [11, 5, 9, 8, 7, 15, 6, 2, 0, 12, 13], 12: [14, 7, 1, 10, 0, 13, 8, 5, 11], 11: [10, 15, 14, 5, 8, 1, 4, 0, 7, 3], 3: [9, 10, 4, 8, 13, 6, 12, 1, 15, 0], 14: [15, 8, 7, 11, 4, 6, 9, 1], 13: [15, 13, 3, 7, 12, 8, 2, 10, 0, 1], 5: [2, 14, 11, 12, 5, 15, 3, 4, 13, 10, 0, 1, 7, 6, 9, 8], 15: [5, 11, 13, 9, 2, 15, 10, 7, 3], 19: [6], 16: [4, 10, 3], 17: [5, 9, 10, 8], 18: [9]}
  conv_init: true
  freeze_model: false
  layer_decay: false
  weight_decay: false

img_size: 336
